name: cbj-hub
base: core20
version: '0.1'
summary: Hub to control smart device from different vendors with one app.
description: |
  CyBear Jinni Hub to controll smart devices from different vendors with one easy to use app.
  It is open source Hub that keeps your data local by default.
  The Hub will extend the devices basic functionality by acting as a leader and sending signals
  to the devices acording to the logic you set it to be.
  The functionality will include activating routines, saving different scense, binding devices so
  that action in one device will triger other actions in different devices and more.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  cbj-hub:
    plugin: dump
    source: .
    override-build: |
      scripts/bashScripts/nativeExecutableMaker.sh  # Downloading dart-sdk for the correct architecture.

      rm -r cbj_hub

      cd scripts/bashScripts/
      ./compileAllCFiles.sh # Have to be executed when working directory is this file location
      cd ../..

      snapcraftctl build

    build-packages:
      - wget
      - unzip
      - gcc
      - g++
    stage-packages:
      - libatlas-base-dev
      - libevent-dev

apps:
  cbj-hub:
    command: CyBear-Jinni_Hub $SNAP
    daemon: simple
    plugs: [network, network-bind, gpio, hardware-observe]
